boxhippo/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm

from users.views import register

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'boxhippo.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    # url(r'^register/', CreateView.as_view(template_name="registration/register.html", form_class=UserCreationForm, success_url="/listings/")),
    url(r'^register/', register),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^listings/', include('listings.urls')),
    url(r'^$', 'listings.views.listings'),
    url(r'^user/', include('users.urls')),
    url(r'^merchants/$', TemplateView.as_view(template_name="basics/landing.html")),
    url(r'base/$', TemplateView.as_view(template_name="basics/base.html")),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

listings/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from listings.views import listings, edit_listing, view_listing, upload_picture, remove_picture

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'boxhippo.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', listings),
    url(r'^view/(?P<lid>\d*|N)/$', view_listing),
    url(r'^edit/(?P<listingID>\d*|N)/$', edit_listing),
    url(r'^upload-pic/(?P<listingID>\d*)/$', upload_picture),
    url(r'^remove-pic/(?P<listingID>\d*)/$', remove_picture),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from users.views import profile, dashboard, start_listing


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'boxhippo.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'profile/$', profile),
    url(r'dashboard/$', dashboard),
    url(r'start-listing/$', start_listing),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

listings/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User
import datetime
import os.path

class Category(models.Model):
  title = models.CharField(max_length = 50, verbose_name = "Main Category")

  def __unicode__(self):
   return self.title

class SubCategory(models.Model):
  title = models.CharField(max_length = 50, verbose_name = "Sub Category")

  def __unicode__(self):
    return self.title

class ProductPicture(models.Model):
  docfile = models.FileField(upload_to = "products", verbose_name = "Product Picture")
  def filename(self):
    return os.path.basename(self.docfile.name)

class Listing(models.Model):
  FREQ_CHOICES = (
    ('D', 'Daily'),
    ('W', 'Weekly'),
    ('M', 'Monthly'),
    ('Q', 'Quarterly'),
    ('S', 'Semi-Annually'),
    ('A', 'Annually'),
  )

  owner = models.ForeignKey(User, verbose_name="Listing Owner")
  title = models.CharField(max_length = 144, default = "Product Title")
  webpage = models.URLField(verbose_name="Listing Webpage", blank=True, null=True)
  category = models.ForeignKey(Category, verbose_name="Category", blank=True, null=True)
  subCategory = models.ForeignKey(SubCategory, verbose_name="Sub Category", blank=True, null=True)
  webpage = models.URLField(verbose_name="Listing Webpage", blank=True, null=True)
  description = models.TextField(verbose_name="Listing Description", blank=True, null=True)
  price = models.DecimalField(max_digits=9, decimal_places=2 , verbose_name="Price", blank=True, null=True)
  rating = models.DecimalField(max_digits=4, decimal_places=2 , verbose_name="Rating", default=0)
  freqType = models.CharField(max_length = 2, verbose_name = "Frequency Type", choices = FREQ_CHOICES, default = "M")
  pic = models.ForeignKey(ProductPicture, verbose_name = "Product Picture", blank = True, null = True)

  def __unicode__(self):
    return self.title

  class Meta:
    ordering = ['title']


class ListingForm(ModelForm):
  class Meta:
    model=Listing
    exclude=('rating', 'owner', 'subCategory', 'pic')

  def __init__(self, *args, **kwargs):
    self.request = kwargs.pop('request', None)
    super(ListingForm, self).__init__(*args, **kwargs)


class PictureForm(ModelForm):
  class Meta:
    model = ProductPicture
    fields = ('docfile',)

listings/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse

from listings.models import Listing, ListingForm, ProductPicture, PictureForm


# Simple function for all listings
def listings(request):
  listings = Listing.objects.all()
  c = {
    'listings': listings,
  }
  return render(request, "pages/listings/listings.html", c)

def view_listing(request, lid):
  listing = Listing.objects.get(pk = lid)
  c = {
    'listing': listing,
  }

  return render(request, "pages/listings/view_listing.html", c)

@login_required
def edit_listing(request, listingID):
  if request.method == 'POST':
    if listingID == 'N':
      form = ListingForm(request.POST)
    else:
      l = Listing.objects.get(pk=listingID)
      form = ListingForm(request.POST, instance=l)
    if form.is_valid():
      tmp = form.save(commit=False)
      tmp.owner = request.user
      tmp.save()
      return HttpResponseRedirect("/user/dashboard/")
  else:
    if listingID == 'N':
      form = ListingForm()
    else:
      l = Listing.objects.get(pk=listingID)
      if l.owner != request.user:
        raise Http404("You cannot edit that")
      form = ListingForm(instance=l)
  return render(request, "pages/listings/edit_listing.html", { 'form':form, })
    

@login_required
def upload_picture(request, listingID):
  listing = Listing.objects.get(pk = listingID)
  redirect_to = reverse('users.views.dashboard')

  if request.method == "POST":
    form = PictureForm(request.POST, request.FILES)
    if form.is_valid():
      newdoc = ProductPicture(docfile = request.FILES['docfile'])
      newdoc.save()
      listing.pic = newdoc
      listing.save()
      return HttpResponseRedirect(redirect_to)
  else:
    form = PictureForm()

  c = {
    'form':form,
    'listing':listing,
  }

  return render(request, "pages/listings/picture.html", c)
    

@login_required
def remove_picture(request, listingID):
  listing = Listing.objects.get(pk = listingID)
  redirect_to = reverse('users.views.dashboard')

  tmp = listing.pic
  listing.pic = None
  listing.save()
  tmp.delete()

  return HttpResponseRedirect(redirect_to)


# Create your views here.

templates/pages/listings/edit_listing.html
{% extends "basics/base.html" %}

{% block content %}
<div class="static-header light">
  <div class="text-heading" style="padding-top:5px">
    <h1>Listing Details</h1>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <form class="form form-register dark" action="" method="POST">
          {% csrf_token %}
          <div class="form-group">
            <label for="title" class="col-lg-2 control-label">{{ form.title.label }}</label>
            <div class="col-lg-10">
              {% load widget_tweaks %}
              {{ form.title|add_class:"form-control" }}
              {% if form.title.errors %}
              <br>
              {{ form.title.errors }}
              {% endif %}
            </div>
          </div>
          <div class="form-group">
            <label for="webpage" class="col-lg-2 control-label">{{ form.webpage.label }}</label>
            <div class="col-lg-10">
              {% load widget_tweaks %}
              {{ form.webpage|add_class:"form-control" }}
              {% if form.webpage.errors %}
              <br>
              {{ form.webpage.errors }}
              {% endif %}
            </div>
          </div>
          <div class="form-group">
            <label for="description" class="col-lg-2 control-label">{{ form.description.label }}</label>
            <div class="col-lg-10">
              {% load widget_tweaks %}
              {{ form.description|add_class:"form-control"|add_class:"form-textarea" }}
              {% if form.description.errors %}
              <br>
              {{ form.description.errors }}
              {% endif %}
            </div>
          </div>
          <div class="form-group">
            <label for="category" class="col-lg-2 control-label">{{ form.category.label }}</label>
            <div class="col-lg-10">
              {% load widget_tweaks %}
              {{ form.category|add_class:"form-control"|attr:"rows:5" }}
              {% if form.category.errors %}
              <br>
              {{ form.category.errors }}
              {% endif %}
            </div>
          </div>
          <div class="form-group">
            <label for="price" class="col-lg-2 control-label">{{ form.price.label }}</label>
            <div class="col-lg-10">
              {% load widget_tweaks %}
              {{ form.price|add_class:"form-control" }}
              {% if form.price.errors %}
              <br>
              {{ form.price.errors }}
              {% endif %}
            </div>
          </div>
          <div class="form-group">
            <label for="freq" class="col-lg-2 control-label">{{ form.freqType.label }}</label>
            <div class="col-lg-10">
              {% load widget_tweaks %}
              {{ form.freqType|add_class:"form-control" }}
              {% if form.freqType.errors %}
              <br>
              {{ form.freqType.errors }}
              {% endif %}
            </div>
          </div>
          <div class="form-group">
            <label for="pic" class="col-lg-2 control-label">{{ form.pic.label }}</label>
            <div class="col-lg-10">
              {% load widget_tweaks %}
              {{ form.pic|add_class:"form-control" }}
              {% if form.pic.errors %}
              <br>
              {{ form.pic.errors }}
              {% endif %}
            </div>
          </div>
          <div class="col-lg-4 col-lg-offset-4">
            <input type="submit" class="btn btn-primary btn-lg btn-block" value="Save"></input>
          </div>
        </form>
      </div>
    </div>
    
  </div>
</div>
{% endblock %}

templates/pages/listings/listings.html
{% extends "basics/base.html" %}

{% block content %}

<div class="container">
<section id ="" class="section dark">
  <div class="panel-group">
    <div class="text-left row">
      {% for l in listings %}
        <div class="col-lg-3" style="padding:15px">
          <div class="col-lg-12" style="background-color:#f8f8f8; padding: 10px; margin:0px; border: 1px solid #e8e8e8">
            <div class="text-center">
              <h6><a href="/listings/view/{{ l.pk }}/" style="color: black;">{{ l.title }}</a></h6>
              <span class="sub-title">
              {% if l.owner.userprofile.companyName %}
              {{ l.owner.userprofile.companyName }}
              {% else %}
              <br>
              {% endif %}
              </span>
              <hr>
            </div>
            <div class="col-lg-12 text-center">
              <div class="img-listing-box">
                <a href="/listings/view/{{ l.pk }}/">
                {% if l.pic %}
                <img src="{{ STATIC_URL }}{{ l.pic.docfile }}" class="img-listing">
                {% else %}
                <img src="{{ STATIC_URL }}img/crate.jpg" class="img-listing">
                {% endif %}
                </a>
              </div>
            </div>
            <div class="col-lg-12" style="height: 100px">
            <br>
              <p>
                <small>
                  {{ l.description|truncatewords:13 }}
                </small>
              </p>
            </div>
            <div class="col-lg-12">
              <div class="text-center">
                <h3>${{ l.price }}
                <h5 style="font-size:15px">{{ l.get_freqType_display }}</h5>
                </h3>
              </div>
              <div class="text-center">
                <a href="/listings/view/{{ l.pk }}/" class="btn btn-primary btn-xs">View Details</a>
                <br><br>
              </div>
            </div>
          </div>
        </div>
        {% if forloop.counter|divisibleby:4 %}
          </div>
	</div>
        <div class="clear"></div>
        <br>
    <div class="text-left row">
        {% endif %}
      {% endfor %}
          </div>
	</div>
        <div class="clear">
        <br>
        </div>
  </div>
</section>
</div>
{% endblock %}

templates/pages/listings/picture.html
{% extends "basics/base.html" %}

{% block content %}
<div class="static-header light">
  <div class="text-heading" style="padding-top:5px;">
    <h1>Product Picture for:<br><h3>{{ listing.title }}</h3></h1>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-lg-offset-3">
        <form class="form form-register dark" action="{% url 'listings.views.upload_picture' listing.pk %}" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-group row">
            <div class="col-lg-4 col-lg-offset-4">
              {{ form.non_field.errors }}
              {{ form.docfile }}
              {{ form.docfile.errors }}
              {{ form.errors }}
            </div>
          </div>
          <div class="form-group">
            <div class="col-lg-6 col-lg-offset-3">
              <br><br>
              <input type="submit" class="btn btn-primary btn-lg btn-block" value="Save"></input>
              <br>
              <a href="" class="btn btn-primary btn-lg btn-block">Cancel</a>
            </div>
          </div>
        </form>
      </div>
    </div>
    
  </div>
</div>
{% endblock %}

templates/pages/listings/view_listing.html
{% extends "basics/base.html" %}

{% block content %}

<div class="container">
<section id ="" class="section dark">
  <div class="panel-group">
    <div class="text-left row" style="background-color:#f8f8f8; padding: 5px; border: 1px solid #e8e8e8">
      <div class="col-lg-12">
        <article>
        <div class="row">
          <div class="col-lg-6">
            <h2>{{ listing.title }}</h2>
            <span class="sub-title">{{ listing.owner.userprofile.companyName }}</span>
          </div>
          <div class="col-lg-6 text-right">
            <h2>${{ listing.price }}<br><small>{{ listing.get_freqType_display }}</small></h2>
          </div>
        </div>
        <hr>
          <div class="col-lg-3 text-middle">
              {% if listing.pic %}
              <img src="{{ STATIC_URL }}{{ listing.pic.docfile }}" class="img-listing">
              {% else %}
              <img src="{{ STATIC_URL }}img/crate.jpg" class="img-listing">
              {% endif %}
              <br>
              <br>
              <a href="{{ listing.webpage }}" class="btn btn-primary">Product Site</a>
              <br><br>
          </div>
          <div class="col-lg-9 col-pull-right">
            <p>
              <small>
                {{ listing.description|linebreaks }}
              </small>
            </p>
          </div>
        </div>
        </article>
      </div>
    </div>
    <div class="clear">
    <br>
    </div>
  </div>
</section>
</div>
{% endblock %}